
name: Executable Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main",]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        os: [windows-latest] # macos-latest, ubuntu-latest, 
      
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nuitka --onefile --assume-yes-for-downloads --enable-plugin=pyside6 --output-dir=build BUAAThesisDowload.py

      # Build python script into a stand-alone exe
      # - uses: Nuitka/Nuitka-Action@main
      #   with:
      #     script-name: main.py
      #     standalone: true
      #     access-token: ${{ secrets.NUITKA_COMMERCIAL_ACCESS_TOKEN }}
      #     onefile: true
      #     enable-plugins: pyside6
      #     disable-console: false
      #     # windows-icon-from-ico: resources/app.ico
      
      # --disable-console
      # --windows-icon-from-ico=resources/app.ico
      # - name: Build Executable (Windows)
      # if: runner.os == 'Windows'
      # shell: powershell
      # run: |
      #   python -m nuitka --onefile --assume-yes-for-downloads --enable-plugin=pyside6 -o BUAAThesisDowload.exe BUAAThesisDowload.py

        

      # build/*.exe
      # build/*.bin
      # build/*.app/**/*
      # Uploads artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*